apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a62c2ujok-nodejs
  janus-idp.io/tekton: a62c2ujok-nodejs
  backstage.io/kubernetes-id: a62c2ujok-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a62c2ujok-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
